# Generated by Django 5.0.4 on 2024-07-07 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='orgId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
